### ISSUE TITLE
Application is crashing.

### ISSUE THREAD

**Issue by vnarendra5a1** [Vidyo/helloworld-vidyo.io-android#2]
Hi,
I am running sample application (provided valid token) on Odroid Xu - 4 (SBC, Android version - 5.1 and with two cameras), the application is crashing with showing Fatal Sig - 8 message (No logs are coming).

**Comment by pfuternik** [comment]
Hello,

Sounds like you have a vidyo.io account since you are using a valid token. Have you tried our VidyoConnector sample from the site? It can be found here:

https://developer.vidyo.io/packages

Do you have that sample working?

Any more info on the crash would help. Assuming you added the jar and the .so files to the project?

Best,
Phil
